### ISSUE TITLE
Subject: Implement Volume API

### ISSUE THREAD

**Issue by herkulano** [RADAR-CNS/RADAR-Dashboard#304]
### Initial load process
Trigger: User navigates to `SubjectPage`
- [x] **1 )** Get volume data from all sources. Fetch has no `startTime` and `endTime` because the frontend doesn't know what's the `effectiveTimeFrame` for the selected sources https://github.com/RADAR-base/RADAR-RestApi/issues/113
- [x] **2 )** Set the resolution for the graphs based on the `effectiveTimeFrame` #306
- [x] **3 )** Set the `timeFrame` in the store and update the `brush` in the volume component #124
- [x] **4 )** Fetch the data for each `visible` graph with the selected `timeFrame`.
- [x] **5 )** Update the x-axis with the selected `timeFrame` #302

### Selection process
Trigger: User changes `brush` selection
- [x] **1 )** Debounce interaction for a few miliseconds, so that we lower the number of calls to the server.
- [x] **2 )** Set the `timeFrame` in the store #124
- [x] **3 )** Fetch the data for each `visible` graph with the selected `timeFrame`.
- [x] **4 )** Update the x-axis with the selected `timeFrame` #302

**Comment by herkulano** [comment]
@mpgxvii this document explains how the volume component and API interacts with the graphs: https://docs.google.com/drawings/d/1zgAg32phe6Le-NGIwmgZpnhaIYVSAcD2p_uCd6dEalU/edit?usp=sharing

This was done some time ago so the names are outdated, but the process is still valid.

![subject architecture](https://user-images.githubusercontent.com/125300/42018847-071d1bfe-7abc-11e8-8e5e-c321ed85a551.png)
